### ISSUE TITLE
[question] What is listening on port 40365?

### ISSUE THREAD

**Issue by Panderine** [hotio/docker-sonarr3#2]
root@sonarr:/# netstat -ltnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8989            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.11:40365        0.0.0.0:*               LISTEN      -

Sorry if this is a silly question but I cannot find what process is that.

**Comment by hotio** [comment]
No idea, but it isn't running on my system.
